---
- name: Docker Compose Services bereitstellen
  hosts: raspberrypi
  become: true

  vars:
    repo_url: "https://github.com/NicoGartmann/docker-config.git"
    repo_dest: "/opt/services"

  tasks:
    - name: Git-Repo mit Compose-Datei klonen
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        force: yes

    - name: Docker Compose Pull (Updates holen)
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: "{{ repo_dest }}"
      register: compose_pull
      changed_when: "'Downloaded' in compose_pull.stdout"

    - name: Docker Compose up (Start/Update der Container)
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: "{{ repo_dest }}"
      register: compose_up
      changed_when: "'Creating' in compose_up.stdout or 'Recreating' in compose_up.stdout"

